from hdx.utilities.downloader import Download
from hdx.utilities.path import temp_dir
from hdx.utilities.retriever import Retrieve

from hdx.scraper.acmad.pipeline import Pipeline


class TestPipeline:
    def test_pipeline(self, configuration, fixtures_dir, input_dir, config_dir):
        with temp_dir(
            "TestAcmad",
            delete_on_success=True,
            delete_on_failure=False,
        ) as tempdir:
            with Download(user_agent="test") as downloader:
                retriever = Retrieve(
                    downloader=downloader,
                    fallback_dir=tempdir,
                    saved_dir=input_dir,
                    temp_dir=tempdir,
                    save=False,
                    use_saved=True,
                )
                pipeline = Pipeline(configuration, retriever, tempdir)
                available_datasets = pipeline.get_available_datasets()
                assert len(available_datasets) == 12
                data_type = "cdi"
                dataset_info = available_datasets[data_type]
                assert dataset_info == {
                    "2015": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2016": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2017": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2018": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2019": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2020": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2021": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2022": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2023": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2024": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2025": {
                        "dekads": ["1", "11", "21"],
                        "months": [
                            "01",
                            "02",
                            "03",
                            "04",
                            "05",
                            "06",
                            "07",
                            "08",
                            "09",
                            "10",
                            "11",
                            "12",
                        ],
                    },
                    "2026": {"dekads": ["1"], "months": ["01"]},
                    "latest_dekad": 1,
                    "latest_month": 1,
                    "latest_year": 2026,
                    "start_year": 2015,
                }
                dataset = pipeline.generate_dataset(data_type, dataset_info)
                assert dataset == {
                    "dataset_date": "[2015-01-01T00:00:00 TO 2026-12-31T23:59:59]",
                    "groups": [
                        {"name": "ago"},
                        {"name": "bdi"},
                        {"name": "ben"},
                        {"name": "bfa"},
                        {"name": "bwa"},
                        {"name": "caf"},
                        {"name": "civ"},
                        {"name": "cmr"},
                        {"name": "cod"},
                        {"name": "cog"},
                        {"name": "com"},
                        {"name": "cpv"},
                        {"name": "dji"},
                        {"name": "dza"},
                        {"name": "egy"},
                        {"name": "eri"},
                        {"name": "esh"},
                        {"name": "eth"},
                        {"name": "gab"},
                        {"name": "gha"},
                        {"name": "gin"},
                        {"name": "gmb"},
                        {"name": "gnb"},
                        {"name": "gnq"},
                        {"name": "ken"},
                        {"name": "lbr"},
                        {"name": "lby"},
                        {"name": "lso"},
                        {"name": "mar"},
                        {"name": "mdg"},
                        {"name": "mli"},
                        {"name": "moz"},
                        {"name": "mrt"},
                        {"name": "mus"},
                        {"name": "mwi"},
                        {"name": "nam"},
                        {"name": "ner"},
                        {"name": "nga"},
                        {"name": "rwa"},
                        {"name": "sdn"},
                        {"name": "sen"},
                        {"name": "sle"},
                        {"name": "som"},
                        {"name": "ssd"},
                        {"name": "stp"},
                        {"name": "swz"},
                        {"name": "syc"},
                        {"name": "tcd"},
                        {"name": "tgo"},
                        {"name": "tun"},
                        {"name": "tza"},
                        {"name": "uga"},
                        {"name": "zaf"},
                        {"name": "zmb"},
                        {"name": "zwe"},
                    ],
                    "name": "acmad-combined-drought-indicator",
                    "subnational": "1",
                    "tags": [
                        {
                            "name": "climate hazards",
                            "vocabulary_id": "b891512e-9516-4bf5-962a-7a289772a2a1",
                        },
                        {
                            "name": "climate-weather",
                            "vocabulary_id": "b891512e-9516-4bf5-962a-7a289772a2a1",
                        },
                        {
                            "name": "drought",
                            "vocabulary_id": "b891512e-9516-4bf5-962a-7a289772a2a1",
                        },
                        {
                            "name": "hazards and risk",
                            "vocabulary_id": "b891512e-9516-4bf5-962a-7a289772a2a1",
                        },
                    ],
                }
                assert dataset.get_resources() == [
                    {
                        "description": "CDI geotiffs by month and dekad for 2026",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2026",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2025",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2025",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2024",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2024",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2023",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2023",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2022",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2022",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2021",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2021",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2020",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2020",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2019",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2019",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2018",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2018",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2017",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2017",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2016",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2016",
                    },
                    {
                        "description": "CDI geotiffs by month and dekad for 2015",
                        "format": "geotiff",
                        "name": "cdi_geotiffs_2015",
                    },
                ]
